import pygame

SCENEDONE = pygame.USEREVENT + 1
STATEDONE = pygame.USEREVENT + 2
DEBUG_TOGGLED = pygame.USEREVENT + 3
ANIMATION_FINISHED = pygame.USEREVENT + 4
ANIMATION_CHANGED = pygame.USEREVENT + 5
ON_ENTER = pygame.USEREVENT + 6
ON_LEAVE = pygame.USEREVENT + 7
ON_PRESSED = pygame.USEREVENT + 8