import pygame
from enum import Enum
from pygame.locals import USEREVENT as U



SCENEDONE = U + 1
STATEDONE = U + 2
DEBUG_TOGGLED = U + 3
ANIMATION_FINISHED = U + 4
ANIMATION_CHANGED = U + 5
ON_ENTER = U + 6
ON_LEAVE = U + 7
ON_PRESSED = U + 8
ON_RELEASE = U + 9
FADESTART = U + 10
FADEEND = U + 11
TRANSITION_START = U + 12
TRANSITION_DONE = U + 13



    

